---
- name: wrapper playbook for kitchen testing "ansible-mysql-hardening"
  hosts: localhost
  vars:
    overwrite_global_mycnf: no
    mysql_root_password: "root"
  roles:
    - geerlingguy.mysql
    - ansible-mysql-hardening
